### PR TITLE
Refactored Collab and Matching Service to MVC

### PR DESCRIPTION
**Pull request by KT27Learn**
# Description

Now upon closing a room, collab service will update a new document "useridToRoom" to store mappings of user's to all their past rooms

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by benedictchuajj — CHANGES_REQUESTED** [review]
MVC looks good but save history doesn't seem to be called with your changes. Did you forget to push something?

**Comment by KT27Learn** [comment]
@benedictchuajj currently the save history is called on the frontend side, should i call it in my collab service side instead?

**Comment by benedictchuajj** [comment]
> @benedictchuajj currently the save history is called on the frontend side, should i call it in my collab service side instead?

can you push your front end code as well? or is it something that should be in another branch?

**Review by benedictchuajj — APPROVED** [review]
@KT27Learn if the front end changes is in another PR, this PR is LGTM

Make sure to update the API list

**Pull request merged**
