### PR TITLE
Implement VideoChat Component

### PR DESCRIPTION
**Pull request by KT27Learn**
# Description

Collab page has a new component (VideoChat) that allows for users to communicate via video conference
Component uses Twilio's video library to implement this service
Using react-draggable for a draggable overlay to allow user to position the video whereever he wants on the page
Will look to implement a mute audio and possibly turn off camera for this in a coming update
I have some commented out code that i will try to implement along with the above new features in another update as currently it is giving me alot of bugs :(

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by KT27Learn** [comment]
@Domszy @benedictchuajj do suggest how I should implement the UI for this

**Comment by KT27Learn** [comment]
Will Integrate with unit tests tomorrow

**Comment by benedictchuajj** [comment]
@KT27Learn Currently the question + code editor is not utilising the entire screen height so there is some space at the bottom where we can have a small video player? 

Though if we do that, we need to ensure that our code editor and question has a fixed height. Otherwise a overlay which can be moved around might be good but harder to implement i guess

**Review by benedictchuajj — APPROVED** [review]
LGTM.

A suggestion i have is have a button that enables them to join the call (maybe at the bottom left) which popups the video call draggable window.

Within that window, I think you can make it a `black screen` or a similar indicator for the other user when they are not connected since Zoom does something similar. (Then can talk about drawing similar experience for UX etc).

Also a button to end the call might be great.

Discussion Diagrams-1

**Pull request merged**
